
enum MtEventType
{
	MT_EVENT_GAMELOADED;
	MT_EVENT_GAMEEND;
	MT_EVENT_PLAYERHIT;
	MT_EVENT_PLAYERDEAD;
	MT_EVENT_TANKCREATED;

	MT_EVENT_UPPRESSED;
	MT_EVENT_UPDEPRESSED;
	MT_EVENT_DOWNPRESSED;
	MT_EVENT_DOWNDEPRESSED;
	MT_EVENT_RIGHTPRESSED;
	MT_EVENT_RIGHTDEPRESSED;
	MT_EVENT_LEFTPRESSED;
	MT_EVENT_LEFTDEPRESSED;

	MT_EVENT_BUTTONAPRESSED;
	MT_EVENT_BUTTONSPRESSED;
}

